# Quick Mobile Setup Script
# Run this to automatically configure your development environment for mobile testing

Write-Host "`n=== KrushiMitra Mobile Setup ===" -ForegroundColor Cyan
Write-Host "This script will help you configure the app for mobile testing`n" -ForegroundColor White

# Step 1: Find your IP address
Write-Host "Step 1: Detecting your IP address..." -ForegroundColor Yellow
$ip = (Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -like "192.168.*" -or $_.IPAddress -like "10.0.*" } | Select-Object -First 1).IPAddress

if ($ip) {
    Write-Host "✓ Found IP address: $ip" -ForegroundColor Green
} else {
    Write-Host "✗ Could not auto-detect IP. Please run 'ipconfig' and find it manually." -ForegroundColor Red
    $ip = Read-Host "Enter your IP address (e.g., 192.168.1.100)"
}

# Step 2: Create/Update .env file
Write-Host "`nStep 2: Updating .env file..." -ForegroundColor Yellow

$envContent = @"
# Mobile Development Configuration
# Auto-generated by mobile-setup.ps1

# Backend URL - Replace IP with your computer's local IP
EXPO_PUBLIC_BACKEND_URL=http://${ip}:3001

# Ollama Server URL - Replace IP with your computer's local IP
EXPO_PUBLIC_OLLAMA_SERVER=http://${ip}:11434

# LLM Mode - hybrid uses local Ollama + cloud fallback
EXPO_PUBLIC_LLM_MODE=hybrid

# Cloud LLM API Keys (get free keys from respective services)
# EXPO_PUBLIC_GROQ_API_KEY=your_groq_api_key_here
# EXPO_PUBLIC_OPENROUTER_API_KEY=your_openrouter_api_key_here

# Firebase Configuration (if using)
# EXPO_PUBLIC_FIREBASE_API_KEY=your_firebase_api_key
# EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN=your_project.firebaseapp.com
# EXPO_PUBLIC_FIREBASE_PROJECT_ID=your_project_id
# EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET=your_project.appspot.com
# EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=your_sender_id
# EXPO_PUBLIC_FIREBASE_APP_ID=your_app_id
"@

Set-Content -Path ".env" -Value $envContent
Write-Host "✓ .env file updated with IP: $ip" -ForegroundColor Green

# Step 3: Configure Ollama
Write-Host "`nStep 3: Configuring Ollama to accept connections..." -ForegroundColor Yellow
[System.Environment]::SetEnvironmentVariable('OLLAMA_HOST', '0.0.0.0:11434', 'User')
[System.Environment]::SetEnvironmentVariable('OLLAMA_ORIGINS', '*', 'User')
Write-Host "✓ Ollama environment variables set" -ForegroundColor Green

# Step 4: Configure Windows Firewall
Write-Host "`nStep 4: Configuring Windows Firewall..." -ForegroundColor Yellow

try {
    # Remove existing rules if they exist
    Remove-NetFirewallRule -DisplayName "KrushiMitra Backend" -ErrorAction SilentlyContinue
    Remove-NetFirewallRule -DisplayName "Ollama" -ErrorAction SilentlyContinue
    
    # Add new rules
    New-NetFirewallRule -DisplayName "KrushiMitra Backend" -Direction Inbound -LocalPort 3001 -Protocol TCP -Action Allow | Out-Null
    New-NetFirewallRule -DisplayName "Ollama" -Direction Inbound -LocalPort 11434 -Protocol TCP -Action Allow | Out-Null
    Write-Host "✓ Firewall rules added for ports 3001 and 11434" -ForegroundColor Green
} catch {
    Write-Host "⚠ Could not configure firewall automatically. You may need to run as Administrator." -ForegroundColor Yellow
    Write-Host "  Manual command: New-NetFirewallRule -DisplayName 'KrushiMitra Backend' -Direction Inbound -LocalPort 3001 -Protocol TCP -Action Allow" -ForegroundColor Gray
}

# Step 5: Display next steps
Write-Host "`n=== Configuration Complete! ===" -ForegroundColor Green
Write-Host "`nNext Steps:" -ForegroundColor Cyan

Write-Host "`n1. Restart Ollama:" -ForegroundColor Yellow
Write-Host "   - Close the current Ollama window" -ForegroundColor White
Write-Host "   - Run: ollama serve" -ForegroundColor White

Write-Host "`n2. Ensure your backend is running:" -ForegroundColor Yellow
Write-Host "   cd path\to\backend" -ForegroundColor White
Write-Host "   npm start" -ForegroundColor White

Write-Host "`n3. Make sure backend listens on 0.0.0.0:" -ForegroundColor Yellow
Write-Host "   In your backend code, use: app.listen(3001, '0.0.0.0')" -ForegroundColor White

Write-Host "`n4. Restart Expo with cache clear:" -ForegroundColor Yellow
Write-Host "   npx expo start -c" -ForegroundColor White

Write-Host "`n5. Connect your mobile device:" -ForegroundColor Yellow
Write-Host "   - Ensure mobile and PC are on the SAME WiFi network" -ForegroundColor White
Write-Host "   - Scan the QR code in Expo Go app" -ForegroundColor White

Write-Host "`n6. Test the connection:" -ForegroundColor Yellow
Write-Host "   Open on your mobile browser: http://${ip}:3001/health" -ForegroundColor White

Write-Host "`n=== Alternative: Use Ngrok ===" -ForegroundColor Cyan
Write-Host "If local IP doesn't work, use ngrok:" -ForegroundColor White
Write-Host "   Terminal 1: ngrok http 3001" -ForegroundColor Gray
Write-Host "   Terminal 2: ngrok http 11434" -ForegroundColor Gray
Write-Host "   Then update .env with the ngrok URLs" -ForegroundColor Gray

Write-Host "`nFor more details, see MOBILE-SETUP.md" -ForegroundColor White
Write-Host "`n" -ForegroundColor White
