import React, { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  SafeAreaView,
  ScrollView,
  Animated,
  Platform,
  Dimensions,
  Modal,
  TextInput,
  Alert,
  RefreshControl,
  ActivityIndicator,
} from 'react-native';
import { useRouter } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { useTranslation } from 'react-i18next';
import ActivityLogService, { 
  ActivityLog,
  logManualFarmActivity
} from './services/ActivityLogService';
import { initializeActivityLogSystem } from './services/ActivityLogInitializer';
import { 
  ArrowLeft, 
  Search,
  Filter,
  Plus,
  Calendar,
  MapPin,
  Eye,
  Smartphone,
  Camera,
  Leaf,
  DollarSign,
  AlertTriangle,
  Droplets,
  Bug,
  Scissors,
  BarChart3,
  CheckCircle,
  Clock,
  AlertCircle,
  X,
  ChevronDown,
  RefreshCw,
  Database,
  Wifi,
  WifiOff
} from 'lucide-react-native';

const { width } = Dimensions.get('window');

// Filter Options Interface
interface FilterOptions {
  farm: string;
  feature: string;
  dateRange: 'today' | 'week' | 'month' | 'all';
  status: string;
}

export default function ActivityTrackingScreen() {
  const { t } = useTranslation();
  const router = useRouter();
  const fadeAnimation = useRef(new Animated.Value(0)).current;
  const slideAnimation = useRef(new Animated.Value(30)).current;
  const activityLogService = ActivityLogService.getInstance();

  // State management
  const [activityLogs, setActivityLogs] = useState<ActivityLog[]>([]);
  const [filteredLogs, setFilteredLogs] = useState<ActivityLog[]>([]);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [showFilters, setShowFilters] = useState(false);
  const [showDetailModal, setShowDetailModal] = useState(false);
  const [selectedLog, setSelectedLog] = useState<ActivityLog | null>(null);
  const [isOnline, setIsOnline] = useState(true);
  const [pendingSyncCount, setPendingSyncCount] = useState(0);
  const [stats, setStats] = useState({
    total: 0,
    today: 0,
    autoGenerated: 0,
    pendingSync: 0
  });

  const [filters, setFilters] = useState<FilterOptions>({
    farm: 'all',
    feature: 'all',
    dateRange: 'all',
    status: 'all'
  });

  useEffect(() => {
    loadActivityLogs();
    startAnimations();
  }, []);

  useEffect(() => {
    applyFilters();
  }, [activityLogs, searchQuery, filters]);

  const startAnimations = () => {
    Animated.parallel([
      Animated.timing(fadeAnimation, {
        toValue: 1,
        duration: 800,
        useNativeDriver: true,
      }),
      Animated.timing(slideAnimation, {
        toValue: 0,
        duration: 600,
        useNativeDriver: true,
      }),
    ]).start();
  };

  const loadActivityLogs = async () => {
    setLoading(true);
    try {
      // Initialize with sample data if first time
      await initializeActivityLogSystem();
      
      // Load logs from the ActivityLogService
      const logs = activityLogService.getLogs();
      const serviceStats = activityLogService.getStats();
      
      setActivityLogs(logs);
      setStats({
        total: serviceStats.total,
        today: serviceStats.today,
        autoGenerated: serviceStats.autoGenerated,
        pendingSync: serviceStats.pendingSync
      });
      setPendingSyncCount(serviceStats.pendingSync);
    } catch (error) {
      console.error('Error loading activity logs:', error);
    } finally {
      setLoading(false);
    }
  };

  const onRefresh = async () => {
    setRefreshing(true);
    await loadActivityLogs();
    setRefreshing(false);
  };

  const applyFilters = () => {
    const filtered = activityLogService.getLogs({
      farm: filters.farm !== 'all' ? filters.farm : undefined,
      feature: filters.feature !== 'all' ? filters.feature : undefined,
      dateRange: filters.dateRange,
      status: filters.status !== 'all' ? filters.status : undefined,
      searchQuery: searchQuery || undefined
    });

    setFilteredLogs(filtered);
  };

  const getFeatureIcon = (feature: string) => {
    switch (feature.toLowerCase()) {
      case 'crop disease detection':
        return <Leaf size={20} color="#4CAF50" />;
      case 'mandi prices':
        return <DollarSign size={20} color="#FF9800" />;
      case 'government schemes':
        return <BarChart3 size={20} color="#2196F3" />;
      case 'carbosafe':
        return <Leaf size={20} color="#8BC34A" />;
      case 'manual activity':
        return <CheckCircle size={20} color="#9C27B0" />;
      case 'ai assistant':
        return <Smartphone size={20} color="#607D8B" />;
      default:
        return <AlertCircle size={20} color="#6B7280" />;
    }
  };

  const getActivityIcon = (activityType: string) => {
    switch (activityType.toLowerCase()) {
      case 'irrigation':
        return <Droplets size={18} color="#2196F3" />;
      case 'pest control':
        return <Bug size={18} color="#F44336" />;
      case 'fertilization':
        return <Scissors size={18} color="#4CAF50" />;
      case 'disease scan':
        return <Camera size={18} color="#FF9800" />;
      case 'price check':
        return <DollarSign size={18} color="#FF5722" />;
      default:
        return <CheckCircle size={18} color="#9E9E9E" />;
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed':
        return '#4CAF50';
      case 'in_progress':
        return '#FF9800';
      case 'failed':
        return '#F44336';
      case 'pending':
        return '#9C27B0';
      default:
        return '#6B7280';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'completed':
        return <CheckCircle size={16} color="#4CAF50" />;
      case 'in_progress':
        return <Clock size={16} color="#FF9800" />;
      case 'failed':
        return <AlertCircle size={16} color="#F44336" />;
      case 'pending':
        return <Clock size={16} color="#9C27B0" />;
      default:
        return <AlertCircle size={16} color="#6B7280" />;
    }
  };

  const getSyncStatusIcon = (syncStatus: string) => {
    switch (syncStatus) {
      case 'synced':
        return <Wifi size={14} color="#4CAF50" />;
      case 'pending':
        return <RefreshCw size={14} color="#FF9800" />;
      case 'failed':
        return <WifiOff size={14} color="#F44336" />;
      default:
        return <Database size={14} color="#6B7280" />;
    }
  };

  const formatTimestamp = (timestamp: Date) => {
    const now = new Date();
    const diffMs = now.getTime() - timestamp.getTime();
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    const diffDays = Math.floor(diffHours / 24);

    if (diffHours < 1) {
      const diffMins = Math.floor(diffMs / (1000 * 60));
      return `${diffMins}m ago`;
    } else if (diffHours < 24) {
      return `${diffHours}h ago`;
    } else if (diffDays === 1) {
      return 'Yesterday';
    } else if (diffDays < 7) {
      return `${diffDays}d ago`;
    } else {
      return timestamp.toLocaleDateString();
    }
  };

  const handleAddManualActivity = () => {
    Alert.prompt(
      'मैन्युअल गतिविधि जोड़ें',
      'गतिविधि विवरण दर्ज करें:',
      [
        {
          text: 'रद्द करें',
          style: 'cancel',
        },
        {
          text: 'जोड़ें',
          onPress: async (details) => {
            if (details && details.trim()) {
              try {
                await logManualFarmActivity(
                  'My Farm - Field A', // Default farm location
                  'General Activity',
                  details.trim()
                );
                await loadActivityLogs(); // Refresh the logs
                Alert.alert('सफलता', 'गतिविधि सफलतापूर्वक जोड़ी गई!');
              } catch (error) {
                Alert.alert('त्रुटि', 'गतिविधि जोड़ने में असफल। कृपया पुनः प्रयास करें।');
              }
            }
          },
        },
      ],
      'plain-text'
    );
  };

  const handleLogPress = (log: ActivityLog) => {
    setSelectedLog(log);
    setShowDetailModal(true);
  };

  const handleBack = () => {
    router.back();
  };

  return (
    <SafeAreaView style={styles.container}>
      <LinearGradient
        colors={['#FFFFFF', '#F1F8E9', '#E8F5E8']}
        style={styles.backgroundGradient}
        start={{ x: 0, y: 0 }}
        end={{ x: 1, y: 0.3 }}
      >
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity style={styles.backButton} onPress={handleBack}>
            <ArrowLeft size={24} color="#4CAF50" />
          </TouchableOpacity>
          
          <View style={styles.headerContent}>
            <Text style={styles.headerTitle}>{t('activityTracking.title')}</Text>
            <Text style={styles.headerSubtitle}>
              {t('activityTracking.subtitle')}
            </Text>
          </View>

          <View style={styles.headerActions}>
            <View style={styles.syncIndicator}>
              {isOnline ? (
                <Wifi size={18} color="#4CAF50" />
              ) : (
                <WifiOff size={18} color="#F44336" />
              )}
            </View>
            {pendingSyncCount > 0 && (
              <View style={styles.syncBadge}>
                <Text style={styles.syncBadgeText}>{pendingSyncCount}</Text>
              </View>
            )}
          </View>
        </View>

        {/* Search and Filter Bar */}
        <View style={styles.searchFilterContainer}>
          <View style={styles.searchContainer}>
            <Search size={20} color="#6B7280" />
            <TextInput
              style={styles.searchInput}
              placeholder={t('activityTracking.searchPlaceholder')}
              value={searchQuery}
              onChangeText={setSearchQuery}
            />
          </View>
          
          <TouchableOpacity 
            style={styles.filterButton}
            onPress={() => setShowFilters(true)}
          >
            <Filter size={20} color="#4CAF50" />
          </TouchableOpacity>
        </View>

        {/* Stats Summary */}
        <View style={styles.summaryRow}>
          <View style={styles.summaryItem}>
            <Text style={styles.summaryNumber}>{stats.total}</Text>
            <Text style={styles.summaryLabel}>{t('activityTracking.totalLogs')}</Text>
          </View>
          <View style={styles.summaryItem}>
            <Text style={styles.summaryNumber}>{stats.today}</Text>
            <Text style={styles.summaryLabel}>{t('activityTracking.todayLogs')}</Text>
          </View>
          <View style={styles.summaryItem}>
            <Text style={styles.summaryNumber}>{stats.autoGenerated}</Text>
            <Text style={styles.summaryLabel}>{t('activityTracking.autoLogs')}</Text>
          </View>
        </View>

        {/* Activity Logs List */}
        <ScrollView 
          style={styles.scrollContainer}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
          refreshControl={
            <RefreshControl
              refreshing={refreshing}
              onRefresh={onRefresh}
              tintColor="#4CAF50"
              colors={['#4CAF50']}
            />
          }
        >
          {loading ? (
            <View style={styles.loadingContainer}>
              <ActivityIndicator size="large" color="#4CAF50" />
              <Text style={styles.loadingText}>{t('activityTracking.loadingLogs')}</Text>
            </View>
          ) : filteredLogs.length === 0 ? (
            <View style={styles.emptyContainer}>
              <Database size={48} color="#D1D5DB" />
              <Text style={styles.emptyTitle}>{t('activityTracking.noLogs')}</Text>
              <Text style={styles.emptySubtitle}>{t('activityTracking.noLogsSubtitle')}</Text>
            </View>
          ) : (
            <Animated.View style={[{
              opacity: fadeAnimation,
              transform: [{ translateY: slideAnimation }],
            }]}>
              {filteredLogs.map((log, index) => (
                <TouchableOpacity
                  key={log.id}
                  style={styles.logCard}
                  onPress={() => handleLogPress(log)}
                  activeOpacity={0.7}
                >
                  <View style={styles.logCardHeader}>
                    <View style={styles.logFeatureContainer}>
                      {getFeatureIcon(log.featureUsed)}
                      <View style={styles.logFeatureInfo}>
                        <Text style={styles.logFeatureText}>{log.featureUsed}</Text>
                        <Text style={styles.logActivityType}>{log.activityType}</Text>
                      </View>
                    </View>
                    
                    <View style={styles.logMetadata}>
                      <Text style={styles.logTimestamp}>{formatTimestamp(log.timestamp)}</Text>
                      <View style={styles.logStatusContainer}>
                        {getStatusIcon(log.status)}
                        {getSyncStatusIcon(log.syncStatus)}
                      </View>
                    </View>
                  </View>

                  <View style={styles.logContent}>
                    <View style={styles.logLocation}>
                      <MapPin size={14} color="#6B7280" />
                      <Text style={styles.logLocationText}>{log.farmLocation}</Text>
                    </View>
                    
                    <Text style={styles.logDetails} numberOfLines={2}>
                      {log.activityDetails}
                    </Text>
                    
                    {log.aiRemarks && (
                      <View style={styles.aiRemarksContainer}>
                        <View style={styles.aiIndicator}>
                          <Text style={styles.aiLabel}>AI</Text>
                        </View>
                        <Text style={styles.aiRemarksText} numberOfLines={1}>
                          {log.aiRemarks}
                        </Text>
                      </View>
                    )}
                  </View>

                  <View style={styles.logFooter}>
                    <View style={styles.logTypeIndicator}>
                      <View style={[
                        styles.logTypeDot,
                        { backgroundColor: log.isAutoGenerated ? '#4CAF50' : '#9C27B0' }
                      ]}>
                      </View>
                      <Text style={styles.logTypeText}>
                        {log.isAutoGenerated ? t('activityTracking.autoGenerated') : t('activityTracking.manual')}
                      </Text>
                    </View>
                    
                    <TouchableOpacity style={styles.viewDetailsButton}>
                      <Eye size={16} color="#4CAF50" />
                      <Text style={styles.viewDetailsText}>{t('activityTracking.viewDetails')}</Text>
                    </TouchableOpacity>
                  </View>
                </TouchableOpacity>
              ))}
            </Animated.View>
          )}
        </ScrollView>

        {/* Floating Action Button */}
        <TouchableOpacity style={styles.fab} onPress={handleAddManualActivity}>
          <Plus size={24} color="#FFFFFF" />
        </TouchableOpacity>

        {/* Filter Modal */}
        <Modal
          visible={showFilters}
          animationType="slide"
          transparent={true}
          onRequestClose={() => setShowFilters(false)}
        >
          <View style={styles.modalOverlay}>
            <View style={styles.filterModal}>
              <View style={styles.filterHeader}>
                <Text style={styles.filterTitle}>{t('activityTracking.filters')}</Text>
                <TouchableOpacity onPress={() => setShowFilters(false)}>
                  <X size={24} color="#6B7280" />
                </TouchableOpacity>
              </View>
              
              {/* Filter content would go here */}
              <ScrollView style={styles.filterContent}>
                {/* Farm Filter */}
                <View style={styles.filterSection}>
                  <Text style={styles.filterSectionTitle}>{t('activityTracking.farmFilter')}</Text>
                  {/* Filter options */}
                </View>
                
                {/* Feature Filter */}
                <View style={styles.filterSection}>
                  <Text style={styles.filterSectionTitle}>{t('activityTracking.featureFilter')}</Text>
                  {/* Filter options */}
                </View>
                
                {/* Date Range Filter */}
                <View style={styles.filterSection}>
                  <Text style={styles.filterSectionTitle}>{t('activityTracking.dateFilter')}</Text>
                  {/* Filter options */}
                </View>
              </ScrollView>
              
              <View style={styles.filterActions}>
                <TouchableOpacity 
                  style={styles.filterResetButton}
                  onPress={() => {
                    setFilters({ farm: 'all', feature: 'all', dateRange: 'all', status: 'all' });
                  }}
                >
                  <Text style={styles.filterResetText}>{t('common.reset')}</Text>
                </TouchableOpacity>
                
                <TouchableOpacity 
                  style={styles.filterApplyButton}
                  onPress={() => setShowFilters(false)}
                >
                  <Text style={styles.filterApplyText}>{t('common.apply')}</Text>
                </TouchableOpacity>
              </View>
            </View>
          </View>
        </Modal>

        {/* Detail Modal */}
        <Modal
          visible={showDetailModal}
          animationType="slide"
          transparent={true}
          onRequestClose={() => setShowDetailModal(false)}
        >
          <View style={styles.modalOverlay}>
            <View style={styles.detailModal}>
              {selectedLog && (
                <>
                  <View style={styles.detailHeader}>
                    <Text style={styles.detailTitle}>{t('activityTracking.activityDetails')}</Text>
                    <TouchableOpacity onPress={() => setShowDetailModal(false)}>
                      <X size={24} color="#6B7280" />
                    </TouchableOpacity>
                  </View>
                  
                  <ScrollView style={styles.detailContent}>
                    {/* Full activity details would go here */}
                    <View style={styles.detailSection}>
                      <Text style={styles.detailSectionTitle}>{t('activityTracking.basicInfo')}</Text>
                      <Text style={styles.detailText}>{selectedLog.activityDetails}</Text>
                    </View>
                    
                    {selectedLog.aiRemarks && (
                      <View style={styles.detailSection}>
                        <Text style={styles.detailSectionTitle}>{t('activityTracking.aiAnalysis')}</Text>
                        <Text style={styles.detailText}>{selectedLog.aiRemarks}</Text>
                      </View>
                    )}
                  </ScrollView>
                </>
              )}
            </View>
          </View>
        </Modal>
      </LinearGradient>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  backgroundGradient: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    shadowColor: '#4CAF50',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1F2937',
    marginBottom: 4,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'Roboto',
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
    fontFamily: Platform.OS === 'ios' ? 'System' : 'Roboto',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  syncIndicator: {
    padding: 8,
  },
  syncBadge: {
    backgroundColor: '#FF5722',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 2,
    minWidth: 20,
    alignItems: 'center',
  },
  syncBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  searchFilterContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 16,
    gap: 12,
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#1F2937',
    fontFamily: Platform.OS === 'ios' ? 'System' : 'Roboto',
  },
  filterButton: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#F1F8E9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  summaryRow: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    marginBottom: 20,
    gap: 12,
  },
  summaryItem: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  summaryNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#4CAF50',
    marginBottom: 4,
  },
  summaryLabel: {
    fontSize: 12,
    color: '#6B7280',
    textAlign: 'center',
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#6B7280',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 60,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#6B7280',
    marginTop: 16,
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
    paddingHorizontal: 40,
  },
  logCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  logCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  logFeatureContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  logFeatureInfo: {
    marginLeft: 12,
    flex: 1,
  },
  logFeatureText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4CAF50',
    marginBottom: 2,
  },
  logActivityType: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  logMetadata: {
    alignItems: 'flex-end',
  },
  logTimestamp: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 4,
  },
  logStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  logContent: {
    marginBottom: 12,
  },
  logLocation: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 4,
  },
  logLocationText: {
    fontSize: 14,
    color: '#6B7280',
  },
  logDetails: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
    marginBottom: 8,
  },
  aiRemarksContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF9',
    borderRadius: 8,
    padding: 8,
    gap: 8,
  },
  aiIndicator: {
    backgroundColor: '#4CAF50',
    borderRadius: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  aiLabel: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  aiRemarksText: {
    flex: 1,
    fontSize: 12,
    color: '#059669',
    fontStyle: 'italic',
  },
  logFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logTypeIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  logTypeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  logTypeText: {
    fontSize: 12,
    color: '#6B7280',
  },
  viewDetailsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  viewDetailsText: {
    fontSize: 12,
    color: '#4CAF50',
    fontWeight: '600',
  },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#4CAF50',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  filterModal: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '80%',
  },
  filterHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  filterTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  filterContent: {
    flex: 1,
    padding: 20,
  },
  filterSection: {
    marginBottom: 24,
  },
  filterSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 12,
  },
  filterActions: {
    flexDirection: 'row',
    padding: 20,
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
  },
  filterResetButton: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  filterResetText: {
    fontSize: 16,
    color: '#6B7280',
    fontWeight: '600',
  },
  filterApplyButton: {
    flex: 1,
    backgroundColor: '#4CAF50',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  filterApplyText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  detailModal: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
  },
  detailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  detailTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  detailContent: {
    flex: 1,
    padding: 20,
  },
  detailSection: {
    marginBottom: 20,
  },
  detailSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  detailText: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
  },
});